Repository Kernel360/E2E1-Orury, pull requests merged in 2023-10, with the labels that each got.

#8 [Feat] #6 전역 gitignore 추가
  .gitignore
Labels: 💻BE, ⚙️Settings

#9 [Feat] #7. Entity 뼈대 작업
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/global/domain/BaseEntity.java
Labels: ✨ Feature, 💻BE

#11 [feat] #10. 게시판 패키지 구성 및 생성 기능 구현
  backend/orury/build.gradle
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/model/BoardDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/model/BoardRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
Labels: ✨ Feature, 💻BE

#15 [feat] #12. Board Read 기능 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
Labels: ✨ Feature, 💻BE

#21 [feat] #16. Board update 로직 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/model/BoardRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
Labels: ✨ Feature, 💻BE

#22 [Feat] #20. Board Delete 기능 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
Labels: ✨ Feature, 💻BE

#24 [feat] #18. POST CRUD 로직 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostViewRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
Labels: ✨ Feature, 💻BE

#26 [feat] #23. 게시판 업데이트 기능 개선
  backend/orury/src/main/java/com/kernel360/orury/OruryApplication.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/global/domain/BaseEntity.java
Labels: 🔨 Refactor, 💻BE

#29 [Feat] #27. 댓글 기능 개발
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/controller/CommentController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/model/CommentDelRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/model/CommentDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/model/CommentRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/global/domain/BaseEntity.java
Labels: 📬 API, ✨ Feature, 💻BE

#31 [feat] #28. 게시판과 게시글 연관관계 맵핑
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/model/BoardDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
Labels: ✨ Feature, 💻BE, 🛢DB

#37 [fix] #34. PostViewRequest 패키지 경로 수정
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostViewRequest.java
Labels: 🐞 BugFix, 💻BE

#38 [fix] Kernel360#34. PostViewRequest 패키지 경로 수정 (추가)
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
Labels: 🐞 BugFix, 💻BE

#40 [Bug] Kernel360#33. 패키지 경로 및 자잘 한 이슈 해결
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
Labels: 🐞 BugFix, 💻BE

#41 [feat] #32. 게시글과 댓글 연관관계 맵핑
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/model/CommentDelRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/model/CommentRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/resources/application.yml
Labels: 🔨 Refactor, ✨ Feature, 💻BE

#43 [refactor] #39. 메서드 및 호출 url 컨벤션 통일
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/controller/CommentController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
Labels: 🔨 Refactor, 💻BE

#47 [Feat] #44. Board, Post, Commnet의 delete 기능에 로깅 기능 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/resources/logback.xml
Labels: ✨ Feature, 💻BE

#50 [feat] #48. 스플래시 화면 개발
  frontend/assets/svg/orury_splash.png
  frontend/assets/svg/orury_splash.svg
  frontend/ios/Flutter/Debug.xcconfig
  frontend/ios/Flutter/Release.xcconfig
  frontend/ios/Podfile
  frontend/lib/data/data_source/local_storage/local_storage.dart
  frontend/lib/data/data_source/remote/remote.dart
  frontend/lib/data/dto/dto.dart
  frontend/lib/data/mapper/mapper.dart
  frontend/lib/data/repository_impl/repository_impl.dart
  frontend/lib/domain/model/model.dart
  frontend/lib/domain/repository/repository.dart
  frontend/lib/domain/usecase/usecase.dart
  frontend/lib/main.dart
  frontend/lib/presentation/pages/home/bloc/bloc.dart
  frontend/lib/presentation/pages/home/home_page.dart
  frontend/lib/presentation/pages/splash/splash_page.dart
  frontend/lib/presentation/routes/route_path.dart
  frontend/lib/presentation/routes/routes.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
  frontend/test/widget_test.dart
Labels: ✨ Feature, 📱FE

#49 [Feat] #42 게시글 pagination 기능 구현
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/global/domain/Api.java
  backend/orury/src/main/java/com/kernel360/orury/global/domain/Pagination.java
Labels: ✨ Feature, 💻BE

#56 [Feat] #45. 메인화면 구현
  frontend/.gitignore
  frontend/lib/main.dart
  frontend/lib/presentation/Board/board.dart
  frontend/lib/presentation/Board/post.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/pubspec.yaml
Labels: 📬 API, ✨ Feature, 💻BE
