Repository Kernel360/E2E1-Orury, pull requests merged in 2023-11, with the labels that each got.

#61 [Feat] #60. 로깅 로직 개선
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostImageEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/global/domain/Listener.java
  backend/orury/src/main/resources/application.yml
  backend/orury/src/main/resources/logback.xml
Labels: 🔨 Refactor, 💻BE

#64 [Feat] Kernel360#58. 메시지 및 상수 enum 처리
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostImageEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/Api.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/BaseEntity.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/Listener.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/Pagination.java
  backend/orury/src/main/java/com/kernel360/orury/global/constants/Constant.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/errors/ErrorMessages.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/info/InfoMessages.java
Labels: 🔨 Refactor, 💻BE

#67 [Feat] #63. 게시판 기능 테스트코드 작성
  backend/orury/src/main/java/com/kernel360/orury/OruryApplication.java
  backend/orury/src/main/java/com/kernel360/orury/global/config/JpaConfig.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/info/InfoMessages.java
  backend/orury/src/test/java/com/kernel360/orury/domain/board/service/BoardServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/comment/service/CommentServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/post/service/PostServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/global/config/JpaConfig.java
  backend/orury/src/test/resources/application.yml
  backend/orury/src/test/resources/logback.xml
Labels: ✅ Test, 💻BE

#68 [Feat] #52. JWT 토큰발급 및 예제 API 구현
  backend/orury/.gitignore
  backend/orury/build.gradle
  backend/orury/src/main/java/com/kernel360/orury/config/CorsConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtAccessDeniedHandler.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtAuthenticationEntryPoint.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtSecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/AuthController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/UserController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/Authority.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/AuthorityRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/exception/DuplicateMemberException.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/exception/NotFoundMemberException.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/AuthorityDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/LoginDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/TokenDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/UserDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/UserResponseDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/CustomUserDetailsService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/UserService.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/Api.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/BaseEntity.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/SecurityUtil.java
  backend/orury/src/main/resources/application.yml
  backend/orury/src/main/resources/data.sql
  backend/orury/src/main/resources/static/index.html
  backend/orury/src/main/resources/templates/index1.html
  backend/orury/src/main/resources/templates/joinForm.html
  backend/orury/src/main/resources/templates/login.html
Labels: 📬 API, 💻BE, 🛢DB

#69 회원가입, 로그인 및 메인화면 개발
  frontend/assets/icons/facebook.svg
  frontend/assets/icons/google.svg
  frontend/lib/components/app_text_form_field.dart
  frontend/lib/core/theme/constant/app_colors.dart
  frontend/lib/global/constants/constant.dart
  frontend/lib/global/messages/user/user_message.dart
  frontend/lib/main.dart
  frontend/lib/presentation/Board/board.dart
  frontend/lib/presentation/Board/comment.dart
  frontend/lib/presentation/Board/post.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/splash/splash_page.dart
  frontend/lib/presentation/pages/user/login_page.dart
  frontend/lib/presentation/pages/user/register_page.dart
  frontend/lib/presentation/routes/route_path.dart
  frontend/lib/presentation/routes/routes.dart
  frontend/lib/resources/vectors.dart
  frontend/lib/utils/extensions.dart
  frontend/lib/values/app_colors.dart
  frontend/lib/values/app_constants.dart
  frontend/lib/values/app_routes.dart
  frontend/lib/values/app_theme.dart
  frontend/pubspec.yaml
Labels: 🎨 Html&css, ✨ Feature, 📱FE

#75 [feat] # 74 Swagger UI추가
  backend/orury/build.gradle
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
Labels: ✨ Feature, 💻BE

#77 [Refactor] #71. 이름에서 이메일로 검증대상 변경
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/AuthController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/UserController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/Authority.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/AuthorityEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/AuthorityRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/AuthorityDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/LoginDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/UserDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/CustomUserDetailsService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/UserService.java
  backend/orury/src/main/java/com/kernel360/orury/global/constants/Constant.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/errors/ErrorMessages.java
Labels: 📬 API, 🔨 Refactor, 💻BE

#80 [Fix] #79. 회원가입과 토큰 버그 수정
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/LoginDto.java
  backend/orury/src/main/java/com/kernel360/orury/global/constants/Constant.java
Labels: 🐞 BugFix, 💻BE

#83 [feat] #76 API 호출 시 사용자 인가 작업 [수정]
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/controller/CommentController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/AuthController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/UserDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/UserService.java
  backend/orury/src/main/java/com/kernel360/orury/global/constants/Constant.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/errors/ErrorMessages.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/info/InfoMessages.java
  backend/orury/src/main/resources/data.sql
Labels: ✨ Feature, 💻BE

#86 [Refactor] #66. 게시글 사진 비정규화 처리
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostImageEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostImageRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/test/java/com/kernel360/orury/domain/board/service/BoardServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/post/controller/PostControllerTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/post/service/PostServiceTest.java
  frontend/assets/icons/kakaotalk.svg
Labels: 📬 API, 🔨 Refactor, ✅ Test, 💻BE

#85 [feat] #76 게시판 인가 설정 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
Labels: ✨ Feature, 💻BE

#88 [Feat] #78 #87. 프론트 로그인, 게시글 관련 api 연동 작업
  frontend/lib/presentation/Board/board_post.dart
  frontend/lib/presentation/Board/post.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
  frontend/lib/presentation/pages/user/register_page.dart
  frontend/lib/presentation/routes/route_path.dart
  frontend/lib/presentation/routes/routes.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 🔨 Refactor, ✨ Feature, 📱FE

#90 [Feat] #89. imgur api 연동
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  frontend/lib/global/messages/board/post_message.dart
  frontend/lib/global/messages/user/user_message.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/pubspec.lock
Labels: 📬 API, ✨ Feature, 📱FE

#93 [Feat] #91. 사진 클릭 시 사진 확대 팝업 노출
  frontend/lib/presentation/Board/post_detail.dart
Labels: ✨ Feature, 📱FE

#95 [Refactor] #94. 게시글/댓글 생성 및 조회시 유저 닉네임 미포함 처리
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/model/CommentRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostRequest.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/test/java/com/kernel360/orury/domain/board/service/BoardServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/post/service/PostServiceTest.java
Labels: 📬 API, 🔨 Refactor, 💻BE

#97 [Feat] #92. 게시글 댓글 생성/수정/삭제 기능 개발
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  frontend/lib/global/messages/board/comment_message.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/Board/post_update.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/routes/route_path.dart
  frontend/lib/presentation/routes/routes.dart
  frontend/pubspec.lock
Labels: ✨ Feature, 📱FE

#96 [feat] #82 refresh 토큰 발급과정 추가
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/AuthController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/RefreshTokenEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/RefreshTokenRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/TokenDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/UserDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/UserService.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/DuplicateMemberException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/GlobalExceptionHandler.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/NotFoundMemberException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/TokenExpiredException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/TokenNotFoundException.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/errors/ErrorMessages.java
  backend/orury/src/main/resources/application.yml
Labels: ✨ Feature, 💻BE

#102 [Feat] #98. 대댓글 기능 추가
  frontend/lib/presentation/Board/comment.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/Board/post_update.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
Labels: 🔨 Refactor, ✨ Feature, 📱FE

#111 [Refactor] #106 로그인 성공시 유저정보를 프론트엔드에 캐싱하는 작업
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/UserController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/model/UserDto.java
  frontend/lib/global/http/http_request.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
Labels: 📬 API, 🔨 Refactor, 📱FE

#114 [Feat] #108. 에러 메시징 처리
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/CustomAuthenticationFailureHandler.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/ApiResponse.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/ApiStatus.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/GlobalExceptionHandler.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/errors/ErrorMessages.java
  backend/orury/src/test/java/com/kernel360/orury/domain/board/service/BoardServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/comment/service/CommentServiceTest.java
  backend/orury/src/test/java/com/kernel360/orury/domain/post/service/PostServiceTest.java
Labels: 🔨 Refactor, 💻BE

#121 [Refactor] #120. GoRouter 통일, #122 게시글 수정 화면 개선, 댓글 수정 기능 개선
  frontend/android/app/build.gradle
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/Board/post_update.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/routes/routes.dart
  frontend/pubspec.yaml
Labels: ❗️Bug, 🔨 Refactor, 📱FE

#123 [Feat] #119. 리프레쉬 토큰 제거 배치 추가
  backend/orury/build.gradle
  backend/orury/src/main/java/com/kernel360/orury/OruryApplication.java
  backend/orury/src/main/java/com/kernel360/orury/batch/job/DeleteExpiredTokenJobConfig.java
  backend/orury/src/main/java/com/kernel360/orury/batch/scheduler/BatchScheduler.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/resources/application.yml
Labels: 📬 API, ✨ Feature, 💻BE

#125 [Refactor] #124. 댓글 순서를 위한 매핑작업, [Fix] #126. 올바른 댓글 순서 보여주기
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  frontend/lib/presentation/Board/post.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
Labels: 🔨 Refactor, 🐞 BugFix, 💻BE, 📱FE

#127 [feat] #110 간단한 SSE 알림 기능 추가
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/SwaggerConfig.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/controller/CommentController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/notification/controller/NotifyController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/notification/db/EmitterRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/notification/service/NotifyService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/UserService.java
  backend/orury/src/main/java/com/kernel360/orury/global/common/SecurityUtil.java
Labels: ✨ Feature, 💻BE

#129 [Fix] #128. 배치 버그 수정
  backend/orury/src/main/java/com/kernel360/orury/batch/job/DeleteExpiredTokenJobConfig.java
Labels: 🐞 BugFix, 💻BE

#133 [Feat] #132. 프런트에서 SSE Client 생성
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/notification/controller/NotifyController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/notification/service/NotifyService.java
  frontend/lib/main.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
Labels: 📬 API, 🔨 Refactor, ✨ Feature, 💻BE, 📱FE

#130 [Refactor] #105. 로그 구분 작업
  backend/orury/src/main/resources/logback.xml
Labels: 🔨 Refactor, 💻BE, ⚙️Settings

#136 [feat] #135. 엑세스 토큰 만료 메시지 수정
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
Labels: ❗️Bug, 💻BE

#138 [Refactor] #112. 토큰 만료됐을 때의 시나리오의 일련의 과정들이 추가 개발
  frontend/lib/global/http/http_request.dart
Labels: 📬 API, 🔨 Refactor, 📱FE

#142 [Feat] #118. 유저 권한 업데이트 기능 추가
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/controller/AdminUserController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/service/AdminUserService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/AuthorityRepository.java
  backend/orury/src/main/resources/templates/index.html
  backend/orury/src/main/resources/templates/layout/tables-data.html
  backend/orury/src/main/resources/templates/user-table.html
Labels: 📬 API, 🎨 Html&css, 💻BE

#143 [Deploy] #141. AWS 설정
  backend/orury/src/main/java/com/kernel360/orury/config/JasyptConfig.java
  backend/orury/src/main/resources/application.yml
  backend/orury/src/main/resources/logback.xml
  backend/orury/src/test/java/com/kernel360/orury/config/JasyptConfigTest.java
  frontend/lib/global/http/http_request.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/Board/post_update.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
  frontend/lib/presentation/pages/user/register_page.dart
  frontend/lib/presentation/pages/user/user_login.dart
  frontend/lib/presentation/pages/user/user_page.dart
Labels: 🔨 Refactor, 🌏 Deploy

#144 Develop to Main merge
  backend/orury/src/main/java/com/kernel360/orury/config/JasyptConfig.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/controller/AdminUserController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/service/AdminUserService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/AuthorityRepository.java
  backend/orury/src/main/resources/application.yml
  backend/orury/src/main/resources/logback.xml
  backend/orury/src/main/resources/templates/index.html
  backend/orury/src/main/resources/templates/layout/tables-data.html
  backend/orury/src/main/resources/templates/user-table.html
  backend/orury/src/test/java/com/kernel360/orury/config/JasyptConfigTest.java
  frontend/lib/global/http/http_request.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/Board/post_update.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
  frontend/lib/presentation/pages/user/register_page.dart
  frontend/lib/presentation/pages/user/user_login.dart
  frontend/lib/presentation/pages/user/user_page.dart
Labels: 🌏 Deploy, 💻BE, 📱FE

#149 [Feat] #148. 로그아웃 기능 및 프론트 메인 화면에 게시판 목록 추가
  frontend/lib/global/http/http_request.dart
  frontend/lib/presentation/Board/boards.dart
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/routes/routes.dart
Labels: 🐞 BugFix, ✨ Feature, 📱FE

#150 [feat] #109 리프레시 토큰과 엑세스 토큰 유효성 확인 로직 변경
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/controller/AuthController.java
  backend/orury/src/main/java/com/kernel360/orury/global/constants/Constant.java
Labels: ✨ Feature, 💻BE

#151 [Refactor] #112. 토큰 만료됐을 때의 시나리오의 일련의 과정들이 추가 개발
  backend/orury/src/main/resources/application.yml
  frontend/lib/global/http/http_request.dart
Labels: 🔨 Refactor, 📱FE

#153 [feat] #152 시큐리티 필터 단 글로벌 예외처리
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtAuthenticationEntryPoint.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/GlobalExceptionHandler.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/RefreshExpiredJwtException.java
Labels: 🐞 BugFix, 💻BE

#155 [Feat] #146. github acion 적용
  .github/workflows/deploy.yml
  backend/orury/appspec.yml
  backend/orury/build.gradle
  backend/orury/scripts/gh_deploy.sh
Labels: 🌏 Deploy, ✨ Feature

#157 [Fix] #156. 리뷰 수정사항 반영
  frontend/lib/global/http/http_request.dart
Labels: 🐞 BugFix, 📱FE

#158 [Feat] #154. openAPI 만들기
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  frontend/lib/global/http/http_request.dart
  frontend/lib/presentation/Board/notice_detail.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
  frontend/lib/presentation/pages/user/notice.dart
  frontend/lib/presentation/pages/user/notice_slide.dart
  frontend/lib/presentation/routes/route_path.dart
  frontend/lib/presentation/routes/routes.dart
Labels: 📬 API, 🔨 Refactor, 💻BE, 📱FE

#163 [Fix] #161. 기술스택 사이즈 조정
  README.md
Labels: 📃 Docs

#159 Develop to Main merge
  README.md
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/controller/BoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  frontend/lib/global/http/http_request.dart
  frontend/lib/presentation/Board/notice_detail.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
  frontend/lib/presentation/pages/user/login_page.dart
  frontend/lib/presentation/pages/user/notice.dart
  frontend/lib/presentation/pages/user/notice_slide.dart
  frontend/lib/presentation/routes/route_path.dart
  frontend/lib/presentation/routes/routes.dart
Labels: 📬 API, 🎨 Html&css, ✨ Feature, 💻BE, 📱FE

#174 [Feat] #171. flyway 적용
  backend/orury/build.gradle
  backend/orury/src/main/java/com/kernel360/orury/domain/user/db/UserEntity.java
  backend/orury/src/main/resources/application.yml
  backend/orury/src/main/resources/db/migration/V1.0.0__alter_column_in_user.sql
Labels: 💻BE, ⚙️Settings

#175 [Refactor] #172. Error Exceoption 구조 변경
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/CustomAuthenticationFailureHandler.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/service/AdminCommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/service/AdminPostService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/service/AdminUserService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/controller/CommentController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/controller/PostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/CustomUserDetailsService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/user/service/UserService.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/GlobalExceptionHandler.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/AuthorizationErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/BoardErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/CertificationErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/CommentErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/ErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/PostErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/ServerErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/code/UserErrorCode.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/dto/ErrorResponse.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/exception/BusinessException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/DuplicateMemberException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/GlobalExceptionHandler.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/NotFoundMemberException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/RefreshExpiredJwtException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/TokenExpiredException.java
  backend/orury/src/main/java/com/kernel360/orury/global/exception/TokenNotFoundException.java
  backend/orury/src/main/java/com/kernel360/orury/global/message/errors/ErrorMessages.java
  backend/orury/src/test/java/com/kernel360/orury/domain/board/service/BoardServiceTest.java
  frontend/lib/global/http/http_request.dart
Labels: 🔨 Refactor, 💻BE, 📱FE

#178 [feat] #152 jwt 토큰관련 예외 추가
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtAuthenticationEntryPoint.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/JwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
Labels: 🐞 BugFix, 💻BE

#180 [Debug] #176. 댓글집계, #179. 좋아요
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  frontend/lib/presentation/Board/post.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
Labels: 🐞 BugFix, 💻BE, 📱FE

#182 [Feat] #118. 어드민 기능구현
  backend/orury/.gitignore
  backend/orury/src/main/java/com/kernel360/orury/config/SecurityConfig.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/TokenProvider.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/admin/AdminJwtAuthenticationEntryPoint.java
  backend/orury/src/main/java/com/kernel360/orury/config/jwt/admin/AdminJwtFilter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/controller/AdminAuthController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/controller/AdminBoardController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/controller/AdminPostController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/controller/AdminUserController.java
  backend/orury/src/main/java/com/kernel360/orury/domain/admin/service/AdminPostService.java
  backend/orury/src/main/resources/application.yml
  backend/orury/src/main/resources/data.sql
  backend/orury/src/main/resources/templates/index.html
  backend/orury/src/main/resources/templates/layout/charts-apexcharts.html
  backend/orury/src/main/resources/templates/layout/charts-chartjs.html
  backend/orury/src/main/resources/templates/layout/charts-echarts.html
  backend/orury/src/main/resources/templates/layout/components-accordion.html
  backend/orury/src/main/resources/templates/layout/components-alerts.html
  backend/orury/src/main/resources/templates/layout/components-badges.html
  backend/orury/src/main/resources/templates/layout/components-breadcrumbs.html
  backend/orury/src/main/resources/templates/layout/components-buttons.html
  backend/orury/src/main/resources/templates/layout/components-cards.html
  backend/orury/src/main/resources/templates/layout/components-carousel.html
  backend/orury/src/main/resources/templates/layout/components-list-group.html
  backend/orury/src/main/resources/templates/layout/components-modal.html
  backend/orury/src/main/resources/templates/layout/components-pagination.html
  backend/orury/src/main/resources/templates/layout/components-progress.html
  backend/orury/src/main/resources/templates/layout/components-spinners.html
  backend/orury/src/main/resources/templates/layout/components-tabs.html
  backend/orury/src/main/resources/templates/layout/components-tooltips.html
  backend/orury/src/main/resources/templates/layout/forms-editors.html
  backend/orury/src/main/resources/templates/layout/forms-elements.html
  backend/orury/src/main/resources/templates/layout/forms-layouts.html
  backend/orury/src/main/resources/templates/layout/forms-validation.html
  backend/orury/src/main/resources/templates/layout/icons-bootstrap.html
  backend/orury/src/main/resources/templates/layout/icons-boxicons.html
  backend/orury/src/main/resources/templates/layout/icons-remix.html
  backend/orury/src/main/resources/templates/layout/pages-blank.html
  backend/orury/src/main/resources/templates/layout/pages-contact.html
  backend/orury/src/main/resources/templates/layout/pages-error-404.html
  backend/orury/src/main/resources/templates/layout/pages-faq.html
  backend/orury/src/main/resources/templates/layout/pages-register.html
  backend/orury/src/main/resources/templates/layout/tables-data.html
  backend/orury/src/main/resources/templates/layout/tables-general.html
  backend/orury/src/main/resources/templates/layout/users-profile.html
  backend/orury/src/main/resources/templates/pages-login.html
Labels: 📬 API, 🎨 Html&css, 💻BE, 📱FE

#184 {Deploy] E2E1-Orury main merge를 위한 커밋
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/global/error/GlobalExceptionHandler.java
Labels: 🐞 BugFix, 💻BE

#183 [Refactor] #177. README 수정 및 고도화
  README.md
Labels: 📃 Docs

#186 [Refactor] #181. 프론트의 MainScreen이 빌드되는 시간이 오래 걸리는 문제
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/resources/application.yml
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
Labels: 📬 API, 🔨 Refactor, 💻BE, 📱FE

#187 Develop to Main merge
  backend/orury/src/main/java/com/kernel360/orury/domain/board/db/BoardEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/board/service/BoardService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/db/CommentRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/comment/service/CommentService.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostEntity.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/db/PostRepository.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/model/PostDto.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostConverter.java
  backend/orury/src/main/java/com/kernel360/orury/domain/post/service/PostService.java
  backend/orury/src/main/resources/application.yml
  frontend/lib/presentation/Board/post_create.dart
  frontend/lib/presentation/Board/post_detail.dart
  frontend/lib/presentation/main/main_screen.dart
Labels: 🌏 Deploy
